# Generated by Django 3.2.9 on 2022-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
