# Generated by Django 3.2.9 on 2022-02-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_targetarea_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='user.occupation'),
        ),
    ]
