# Generated by Django 3.2.9 on 2022-02-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_vehicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='profile',
        ),
    ]
