# Generated by Django 3.2.9 on 2022-02-22 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_profile_img_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='profile',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='auth.user'),
            preserve_default=False,
        ),
    ]
