# Generated by Django 3.2.9 on 2022-03-02 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('customer_location', models.CharField(max_length=500)),
                ('pay', models.BooleanField(default=False)),
                ('shipment_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.location')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
