# Generated by Django 3.2.9 on 2022-03-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_bill_offer_orderactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
