# Generated by Django 3.2.9 on 2022-03-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_store_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.location'),
        ),
    ]
