# Generated by Django 3.2.9 on 2022-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_shipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_img',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
