# Generated by Django 3.2.9 on 2022-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220304_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_text',
            field=models.TextField(),
        ),
    ]
