# Generated by Django 3.2.9 on 2022-03-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_bill_bill_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
