# Generated by Django 3.2.9 on 2022-03-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_bills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='order',
        ),
    ]
